{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "KAPUSTA API docs",
    "description": "Description of KAPUSTA API",
    "license": {}
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [
    { "url": "http://localhost:3000" },
    { "url": "https://kapusta-finance-tracker.herokuapp.com/" }
  ],
  "tags": [
    {
      "name": "Users",
      "description": "Authorization endpoints"
    },
    {
      "name": "Transactions",
      "description": "Transactions endpoints"
    },
    {
      "name": "Reports",
      "description": "Reports endpoints"
    },
    {
      "name": "Categories",
      "description": "Categories endpoints"
    }
  ],
  "paths": {
    "/api/user/signup": {
      "post": {
        "tags": ["Users"],
        "summary": "User registration",

        "parameters": [],

        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/user/verify": {
      "get": {
        "tags": ["Users"],
        "summary": "User verification",

        "parameters": [
          {
            "type": "string",
            "required": true,
            "description": "User's verifu token",
            "example": "56qhj124786qjhdayutjhkdsfu87sd6rwjk.djhjhd"
          }
        ],

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/user/login": {
      "post": {
        "tags": ["Users"],
        "summary": "User login",

        "parameters": [],

        "security": [{ "Bearer": [] }],

        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/user/logout": {
      "get": {
        "tags": ["Users"],
        "summary": "User logout",

        "parameters": [],

        "security": [{ "Bearer": [] }],

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          }
        }
      }
    },
    "/api/user/current": {
      "get": {
        "tags": ["Users"]
      }
    },
    "/api/user/balance": {
      "get": {
        "tags": ["Users"]
      },
      "post": {
        "tags": ["Users"]
      },
      "patch": {
        "tags": ["Users"]
      }
    },
    "/api/transactions/expense/": {
      "post": {
        "tags": ["Transactions"],
        "summary": "Add user expense transaction ",

        "parameters": [
          {
            "in": "paths",
            "name": "categoryId",
            "required": true,
            "type": "string",
            "description": "Transaction category Id"
          }
        ],

        "security": [{ "Bearer": [] }],

        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddExpenseTransactionRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Vasiya"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "verifyToken": {
            "type": "string",
            "description": "User's verifu token",
            "example": "56qhj124786qjhdayutjhkdsfu87sd6rwjk.djhjhd"
          }
        },

        "example": {
          "status": "success",
          "code": 200,
          "result": {
            "name": "Vasiya",
            "email": "vasiya1999@gmail.com",
            "verifyToken": "56qhj124786qjhdayutjhkdsfu87sd6rwjk.djhjhd"
          }
        }
      },
      "VerifyRequest": {},
      "VerifyResponse": {
        "type": "object",
        "properties": {
          "status": "success",
          "code": 200,
          "data": {
            "message": "Verification successful"
          },
          "example": {
            "status": "success",
            "code": 200,
            "data": {
              "message": "Verification successful"
            }
          }
        }
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "object",

        "properties": {
          "status": "success",
          "code": 200,
          "result": {
            "token": {
              "type": "string",
              "description": "User's token",
              "example": "56qhj124786qjhdayutjhkdsfu87sd6rwjk.djhjhd"
            },
            "name": {
              "type": "string",
              "description": "User's name",
              "example": "Vasiya"
            },
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "balance": {
              "type": "string",
              "description": "User's balance",
              "example": "54000"
            }
          }
        },

        "example": {
          "status": "success",
          "code": 200,
          "result": {
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTg5OTQyMzQ1OGVhNzBmZTgxMTM3NDgiLCJpYXQiOjE2MzcxNjMxMDN9.Ex1pQwkyGqHwyKDgue3wz8x19OtuWzt8bh-ZoDxJlTk",
            "user": {
              "name": "Vyacheslav",
              "email": "grachv77@gmail.com",
              "balance": 54000
            }
          }
        }
      },
      "LogoutResponce": {
        "type": "object",
        "properties": {}
      },
      "CurrentUserRespons": {
        "type": "object",
        "properties": {}
      },
      "CurrentUserBalanceResponse": {
        "type": "object",
        "properties": {}
      },
      "AddCurentUserBalanceRequest": {
        "type": "object",
        "required": [],
        "properties": {}
      },
      "AddCurentUserBalanceResponse": {
        "type": "object",
        "properties": {}
      },
      "UpdateCurrentUserBalanceResponce": {
        "type": "object",
        "properties": {}
      },
      "AddExpenseTransactionRequest": {
        "type": "object",
        "required": [],
        "properties": {}
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
